### ISSUE TITLE
[ BUG ] I've get a error when I try to install dpm

### ISSUE THREAD

**Issue by jheysaav** [dpmland/dpm#19]
> If not follow this guide the issue can be closed :warning:

**Describe the bug** A clear and concise description of what the bug is.
I've followed the guide in the readme to install the stable version, but in the process, Deno returns an error

**To Reproduce** Steps to reproduce the behavior:

1. Exec `deno run -A --unstable https://deno.land/x/dpm/install.ts stable`
2. Expect the error

**Expected behavior** A clear and concise description of what you expected to
happen.
I expected get dpm on my machine

**Screenshots** If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/84047886/195178721-da7c7dad-4972-434f-8585-30055e9c1c32.png)

**Desktop (please complete the following information):**

- OS: Manjaro Linux
- Browser *Doesn't apply*
- Version *The OS is rolling release, but the kernel version is 5.19.14-1 and the Deno version is 1.26.1 (release, x86_64-unknown-linux-gnu)*

**Smartphone (please complete the following information):**

- Device: *Doesn't apply*
- OS: *Doesn't apply*
- Browser *Doesn't apply*
- Version *Doesn't apply*

**Additional context** Add any other context about the problem here.
None

**Comment by TeoDev1611** [comment]
Look like the compiler not found the `deno dl` can you try this installer:
`deno run -A --unstable https://raw.githubusercontent.com/dpmland/dpm/dev/install.ts stable`

Or if the error continues maybe is the deno compiler error please report this or can you install dpm with this: `deno install -Afq --import-map https://deno.land/x/dpm@v0.1.1/import_map.json  https://deno.land/x/dpm@v0.1.1/dpm.ts`

**Comment by jheysaav** [comment]
The solution found, thank you for the help.
